name: '🔥 Bug Report'
description: 'Report a bug in the project. Please provide as much detail as possible to help us understand and fix the issue.'
title: '[Bug] '
labels:
    - 'Problem: Bug'
body:
    - type: textarea
      id: summary
      attributes:
          label: 'Summary'
          description: 'A brief description of the bug'
          placeholder: 'Example: Dashboard appears blank after login'
      validations:
          required: true

    - type: textarea
      id: expected
      attributes:
          label: 'Expected Behavior'
          description: 'What should happen instead'
      validations:
          required: true

    - type: textarea
      id: links and screenshots
      attributes:
          label: 'Related Links'
          description: 'Links to related issues, PRs, or documentation'
      validations:
          required: false
