name: '🎨 Design/Interface'
description: 'Suggest a design proposal for the project. Please provide as much detail as possible to help us understand and evaluate your suggestion.'
title: '[Design] '
labels:
    - 'Type: Design'
body:
    - type: textarea
      id: summary
      attributes:
          label: 'Summary'
          description: 'A brief description of the design proposal'
          placeholder: 'Example: Consider redesigning the authentication flow'
      validations:
          required: true

    - type: textarea
      id: requirements
      attributes:
          label: 'Requirements'
          description: 'Please list the requirements that need to be met'
      validations:
          required: false

    - type: textarea
      id: links and screenshots
      attributes:
          label: 'Related Links'
          description: 'Links to related issues, PRs, or documentation'
      validations:
          required: false
